name: Generate 3D Contribution Particles

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.5.2
        with:
          token: ${{ secrets.GH_PAT }}
          user_name: QuantumCoderrr  # Replace with your GitHub username

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Updated 3D Contribution Particles" || exit 0
          git push https://QuantumCoderrr:${{ secrets.GH_PAT }}@github.com/QuantumCoderrr/QuantumCoderrr.git


